In [1]:
import numpy as np

In [2]:
numbers = np.arange(0,101)
print(numbers)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [5]:
between50and75 = np.where((numbers>=50) & (numbers <=75))
numbers[between50and75]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75])

In [9]:
copyNumbers = numbers.copy()
copyNumbers = numbers[0:51] * 100
print(copyNumbers)

[   0  100  200  300  400  500  600  700  800  900 1000 1100 1200 1300
 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700
 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100
 4200 4300 4400 4500 4600 4700 4800 4900 5000]


In [14]:
higherThanLower = numbers[::-1]
print(higherThanLower)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1   0]


In [17]:
listOfOnes = np.ones((3,3))
listOfZeros = np.zeros((3,3))

verticalStack = np.vstack((listOfOnes, listOfZeros))
horizontalStack = np.hstack((listOfOnes, listOfZeros))

print(verticalStack, "\n", horizontalStack)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [18]:
arrayLin = np.linspace(0,5,10)
print(arrayLin)
dialNP = np.diag([1,5,10])
print(dialNP)
matrizOf8 = np.full((5,5), 8)
print(matrizOf8)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[ 1  0  0]
 [ 0  5  0]
 [ 0  0 10]]
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [19]:
np.random.seed(101)
randomNumber = np.random.randn()
randomNumber

2.706849839399938

In [22]:
ceil = np.ceil(randomNumber)
floor = np.floor(randomNumber)
roundNP = np.round(randomNumber, 5)

print(ceil)
print(floor)
print(roundNP)

3.0
2.0
2.70685


In [44]:
list1 = np.array(([1,2,3], ["A", "B", "C"]))
list2 = np.array(([4,5,6], ["D", "E" , "F"]))
list3 = np.array(([7,8,9], ["G", "H", "I"]))

allList = np.array((list1, list2, list3))
allList


array([[['1', '2', '3'],
        ['A', 'B', 'C']],

       [['4', '5', '6'],
        ['D', 'E', 'F']],

       [['7', '8', '9'],
        ['G', 'H', 'I']]], dtype='<U11')

In [45]:
allList[1][0][2]

'6'

In [35]:
list2withoutColumn0 = np.delete(list2, 0, axis = 0)
list2withoutColumn0

array([['D', 'E', 'F']], dtype='<U11')

In [37]:
list3X3 = np.repeat(list3, 3, axis = 1)
list3X3

array([['7', '7', '7', '8', '8', '8', '9', '9', '9'],
       ['G', 'G', 'G', 'H', 'H', 'H', 'I', 'I', 'I']], dtype='<U11')