In [1]:
import numpy as np


In [45]:
np.random.seed(101)

NumberSet = np.random.randint(1,100, 50)
print(NumberSet)
CopyNumberSet = NumberSet.copy()

CopyNumberSet
          

[96 12 82 71 64 88 76 10 78 41  5 64 41 61 93 65  6 13 94 41 50 84  9 30
 60 35 45 73 20 11 77 96 88  1 74  9 63 37 84 29 64  8 11 53 57 39 74 53
 19 72]


array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41,  5, 64, 41, 61, 93, 65,  6,
       13, 94, 41, 50, 84,  9, 30, 60, 35, 45, 73, 20, 11, 77, 96, 88,  1,
       74,  9, 63, 37, 84, 29, 64,  8, 11, 53, 57, 39, 74, 53, 19, 72])

In [46]:
CopyNumberSet = CopyNumberSet.reshape(5,10)
print(CopyNumberSet)

[[96 12 82 71 64 88 76 10 78 41]
 [ 5 64 41 61 93 65  6 13 94 41]
 [50 84  9 30 60 35 45 73 20 11]
 [77 96 88  1 74  9 63 37 84 29]
 [64  8 11 53 57 39 74 53 19 72]]


In [47]:
CopyNumberSet[0:2,:]

array([[96, 12, 82, 71, 64, 88, 76, 10, 78, 41],
       [ 5, 64, 41, 61, 93, 65,  6, 13, 94, 41]])

In [8]:
CopyNumberSet[:,3:5]

array([[71, 64],
       [61, 93],
       [30, 60],
       [ 1, 74],
       [53, 57]])

In [48]:
CopyNumberSet = np.insert(CopyNumberSet, 4, 55)
CopyNumberSet = np.delete(CopyNumberSet, 30)
CopyNumberSet = np.append(CopyNumberSet, 45)
print(CopyNumberSet)

[96 12 82 71 55 64 88 76 10 78 41  5 64 41 61 93 65  6 13 94 41 50 84  9
 30 60 35 45 73 20 77 96 88  1 74  9 63 37 84 29 64  8 11 53 57 39 74 53
 19 72 45]


In [23]:
MaxCopyNumberSet = np.max(CopyNumberSet)
MinCopyNumberSet = np.min(CopyNumberSet)
AvgCopyNumberSet = np.mean(CopyNumberSet)
MedianCopyNumberSet = np.median(CopyNumberSet)
StdCopyNumberSet = np.std(CopyNumberSet)

print(MaxCopyNumberSet, "\n", MinCopyNumberSet,"\n", AvgCopyNumberSet , "\n",MedianCopyNumberSet, "\n",StdCopyNumberSet)

96 
 1 
 50.52 
 55.0 
 29.230285664016353


In [24]:
UniqueValues = np.unique(CopyNumberSet)
print(UniqueValues)

[ 1  5  6  8  9 10 11 12 13 19 20 29 30 35 37 39 41 45 50 53 57 60 61 63
 64 65 71 72 73 74 76 77 78 82 84 88 93 94 96]


In [25]:
UniqueListEven = np.array(())
for i in UniqueValues:
    if i % 2==0:
        UniqueListEven = np.append(UniqueList, i)
        
print(UniqueListEven)

[ 6.  8. 10. 12. 20. 30. 50. 60. 64. 72. 74. 76. 78. 82. 84. 88. 94. 96.]


In [29]:
DogsVSCats = np.random.choice(["Dog", "Cat"], 100)
Dogs = sum(DogsVSCats == "Dog")
Cats = sum(DogsVSCats == "Cat")
print(f"There are {Dogs} dogs and {Cats} cats")

There are 51 dogs and 49 cats


In [53]:
np.savetxt("uniquenumbers.csv", UniqueValues, fmt="%d")

In [30]:
def CircleArea(r):
    return np.pi*r**2

print(CircleArea(6))

113.09733552923255
