# Numpy Personal Handbook

In [2]:
import numpy as np

## You can make list and matrix

In [2]:
list1D = [1,2,3,4,5,6]
list2D = [[1,2,3], [4,5,6]]

## Get elements from list and matrix

In [61]:
print(list1D[0:4])
print(list2D[1][2])

[1, 2, 3, 4]
6


In [65]:
backUpList1D = list1D.copy()
backUpList2D = list2D.copy()
backUpList1D[2] = 33

print(backUpList1D)

[1, 2, 33, 4, 5, 6]


In [11]:
npList1D = np.array(list1D)
nplist2D = np.array(list2D)
print(f"This is a one dimensional list: \n {npList1D}")
print(f"And this a two dimensional list: \n {nplist2D}")

This is a one dimensional list: 
 [1 2 3 4 5 6]
And this a two dimensional list: 
 [[1 2 3]
 [4 5 6]]


In [67]:
print(nplist2D[:,1])
print(nplist2D[1,2])

[2 5]
6


## You can make numerical list

In [12]:
npRange = np.arange(1,11)
print(npRange)

[ 1  2  3  4  5  6  7  8  9 10]


# You can make basic math

In [24]:
mathList = np.array([1,2,3,4,5])
mathList2 = np.array([2,2,2,2,2])

print(mathList+mathList2)
print(mathList-mathList2)
print(mathList*mathList2)
print(mathList/mathList2)
print(mathList**mathList2)
print(mathList%mathList2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[1 0 1 0 1]


# Counting Values

In [33]:
print(f"Number that are equal in two arrays: {np.sum(mathList==mathList2)}")
print(f"Number that are different in two arrays: {np.sum(mathList!=mathList2)}")
print(f"Another way to know if you have differnt values in two array with boolean: {np.array_equal(mathList, mathList2)}")

Number that are equal in two arrays: 1
Number that are different in two arrays: 4
Another way to know if you have differnt values in two array with boolean: False


## You can make matrix with a diagonal

In [30]:
matrixOne = np.eye(4)
print(f"By default it is always to be ones \n {matrixOne}")
matrix1to4 = np.diag([1,2,3,4])
print(f"In this one you can selected which numbers you like to be on the diagonal \n {matrix1to4}")

By default it is always to be ones 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
In this one you can selected which number you like to be on the diagonal 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# You can make matrix with specific numbers

In [5]:
zerosList = np.zeros((3,4))
print(zerosList)
onesList = np.ones((5,6))
print(onesList)
sevensList = np.full((5,5), 7)
print(sevensList)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


## You can reshape with matrix dimentions

In [15]:
matrix2X5= np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(f"{matrix2X5.shape} \n {matrix2X5}")
matrix5X2 = matrix2X5.reshape((5,2))
print(f"{matrix5X2.shape}\n {matrix5X2}")

(2, 5) 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(5, 2)
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# You can know more informacion about the matrix or array

In [20]:
print(matrix5X2.ndim)
print(matrix5X2.size)
print(matrix5X2.shape)
print(matrix5X2.dtype)

2
10
(5, 2)
int32


# You can turn an array into a list

In [35]:
matrixToList = matrix2X5.tolist()
print(matrixToList)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


## Save and Load Information

In [ ]:
np.save("matrix5X2", matrix5X2)

np.savetxt("matrix5X2.csv", matrix5X2, fmt = "%d")

np.load("matrix5X2.npy")

np.load("matrix5X2.csv", dtype = int)

## You can create a list from a start and end but inside with how many numbers would you like

In [31]:
from1To10In20Numbers = np.linspace(1,10,20)
print(from1To10In20Numbers)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## Random Number

In [7]:
np.random.seed(101)
randomNumberFrom0to1 = np.random.rand(1)
print(f"Random float Number from 0 to 1: {randomNumberFrom0to1}")
randomNumberInteger = np.random.randint(1,10)
print(f"Random Integer Number: {randomNumberInteger}")
randomUniform = np.random.uniform(3,9,10)
print(f"Random number with a uniform distribution {randomUniform}")
randomNormal = np.random.normal(1,10,3)
print("Three random numbers that could be negative and positive: ",randomNormal)
dogORcat = np.random.choice(["Dog", "Cat"])
print("A random choice between dog or cat: ", dogORcat)

Random float Number from 0 to 1: [0.51639863]
Random Integer Number: 2
Random number with a uniform distribution [8.71610615 8.90668569 3.00798237 6.20466528 4.73605376 6.46294006
 4.59713136 7.67332748 8.3523833  3.45409139]
Three random numbers that could be negative and positive:  [10.10359137 24.9810814  15.31259377]
A random choice between dog or cat:  Dog


## Aggregate functions

In [49]:
nparray = np.array([1,2,3])
nparray2 = np.array([1.2,5.6,3.5])
print(f"{nparray} \n {nparray2}")

[1 2 3] 
 [1.2 5.6 3.5]


In [60]:
print(nparray.max())
print(nparray.argmax()) #Give you the position of the max element
print(nparray.min())
print(nparray.argmin()) #Give you the position of the min element
print(nparray.mean())

print(nparray.std())
print(np.sqrt(nparray))
print(np.exp(nparray))
print(np.sin(nparray))
print(np.log(nparray))

print(np.ceil(nparray2))
print(np.floor(nparray2))
print(np.round(nparray2))


3
2
1
0
2.0
0.816496580927726
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]
[2. 6. 4.]
[1. 5. 3.]
[1. 6. 4.]


## Conditional Formatting

In [22]:
randomPick = np.random.randint(1,100, 75)
print(randomPick)

[20 11 77 96 88  1 74  9 63 37 84 29 64  8 11 53 57 39 74 53 19 72 16 45
  1 13 18 76 80 98 94 25 37 64 20 36 31 11 61 21 28  9 87 27 88 47 48 55
 87 10 46  3 19 59 93 12 11 95 36 29  4 84 85 48 15 70 61 70 52  7 89 72
 69 24 36]


In [83]:
lessThan50 = randomPick < 50
print(randomPick[lessThan50])
print(f"There are {np.count_nonzero(randomPick[lessThan50])} numbers below 50")

[ 6 13 41  9 30 35 45 20 11  1  9 37 29  8 11 39 19 16 45  1 13 18 25 37
 20 36 31 11 21 28  9 27 47 48 10 46  3 19 12 11 36 29]
There are 42 number below 50


In [74]:
all30 = (randomPick >=30) & (randomPick <=39)
print(randomPick[all30])

[30 35 37 39 37 36 31 36]


In [23]:
randomPickHightThan80 = np.where(randomPick>80)
print(randomPick[randomPickHightThan80])

[96 88 84 98 94 87 88 87 93 95 84 85 89]


## Sorting

In [78]:
sortedRandomPick = np.sort(randomPick)
print(sortedRandomPick)

[ 1  1  3  6  8  9  9  9 10 11 11 11 11 12 13 13 16 18 19 19 20 20 21 25
 27 28 29 29 30 31 35 36 36 37 37 39 41 45 45 46 47 48 50 53 53 55 57 59
 60 61 61 63 64 64 65 72 73 74 74 76 77 80 84 84 87 87 88 88 93 93 94 94
 95 96 98]


In [79]:
revereSortRandomPick = sortedRandomPick[::-1]
print(revereSortRandomPick)

[98 96 95 94 94 93 93 88 88 87 87 84 84 80 77 76 74 74 73 72 65 64 64 63
 61 61 60 59 57 55 53 53 50 48 47 46 45 45 41 39 37 37 36 36 35 31 30 29
 29 28 27 25 21 20 20 19 19 18 16 13 13 12 11 11 11 11 10  9  9  9  8  6
  3  1  1]


## Add, delete or insert info

In [92]:
normalList = np.array([1,2,3,4,5])
normalList = np.append(normalList, 6)
print(normalList)
normalList = np.delete(normalList, 3) #position
print(normalList)
normalList = np.insert(normalList, 1, 100) #First the position and then the value
print(normalList)

[1 2 3 4 5 6]
[1 2 3 5 6]
[  1 100   2   3   5   6]


# You can add more arrays into a another array

In [40]:
listNumber1 = np.array([1,1,1,1])
listNumber2 = np.array([2,2,2,2])

horizontalStack = np.hstack((listNumber1,listNumber2))
verticalStack = np.vstack((listNumber1,listNumber2))

print("Horizontal: ")
print(horizontalStack, "\n")
print("Vertical:")
print(verticalStack, "\n")

Horizontal: 
[1 1 1 1 2 2 2 2] 

Vertical:
[[1 1 1 1]
 [2 2 2 2]] 



# Or Repeat an array

In [49]:
repeatVertical = np.repeat(listNumber1,2,  axis=0)
repeatHorizontal = np.repeat(matrix5X2, 2, axis=1)

print("Vertical:")
print(repeatVertical,  "\n")
print("Horizontal: ")
print(repeatHorizontal,  "\n")

Vertical:
[1 1 1 1 1 1 1 1] 

Horizontal: 
[[ 1  1  2  2]
 [ 3  3  4  4]
 [ 5  5  6  6]
 [ 7  7  8  8]
 [ 9  9 10 10]] 



# To select the unique values

In [51]:
duplicateList=np.array([1,2,3,2,1,3,2,1,2,3,2,1])
print(duplicateList)
uniqueList = np.unique(duplicateList)
print(uniqueList)

[1 2 3 2 1 3 2 1 2 3 2 1]
[1 2 3]


# You can transpose arrays

In [57]:
listNumberMatrix = np.array([listNumber1, listNumber2])

print("Array Orgininal")
print(listNumberMatrix, "\n")

print("Array Transposed")
transposeListNumberMatrix = np.transpose(listNumberMatrix)
print(transposeListNumberMatrix, "\n")


Array Orgininal
[[1 1 1 1]
 [2 2 2 2]] 

Array Transposed
[[1 2]
 [1 2]
 [1 2]
 [1 2]] 

